version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # Flask应用服务
  app:
    image: polarsnowleopard/ioeb-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICES_BASE_PATH=/app/data/services
      - PORT_RANGE_START=27000
      - PORT_RANGE_END=28000
      - SERVICE_HOST_URL=http://fdueblab.cn
    env_file:
      - ./.env

    volumes:
      - app_data:/app/uploads
      - app_db:/app/instance
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket挂载，允许容器内操作Docker
      - /data/ioeb_services:/app/data/services      # 服务存储目录，与宿主机共享
    networks:
      - app-network  # 加入现有网络
  #   depends_on:
  #     - redis

  # # Redis缓存服务
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   volumes:
  #     - redis_data:/data

  # # Nginx反向代理
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./static:/var/www/static
  #   depends_on:
  #     - app

volumes:
  app_data:
  app_db:
  redis_data:
